use_structure_encoder: true
args:
  _target_: disco.model.modules.lmpnn.LigandMPNN
  ca_only: False
  arg_pack_side_chains: False
  set_eval: False
  k_neighbors: 48
  device: "cuda" # will be overridden by InferenceRunner.init_model with the active device
  batch_size: 4
  embed_diffusion_time: false
